# .github/workflows/ci.yml

name: Continuous Integration

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    name: Build and Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Test on multiple Node versions ✅

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  assign-reviewers:
    name: Assign PR Reviewers
    runs-on: ubuntu-latest
    needs: build-and-test   # only run if all Node versions pass ✅
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR reviewers
        uses: peter-evans/assign-reviewers@v3
        with:
          reviewers: |
            XSTRANGER-7
            YASH-YADAV-dynamo 
          team-reviewers: |
            maintainers
          additional-assignees: github-copilot
